-- ─────────────────────────────────────────────────────────────────────────
-- 005_iso27001_controls.sql
--
-- Run ONCE against the MASTER / platform Supabase database — the same one
-- holding `accounts`, `users`, `security_audit_log`.
--
-- WHY IT EXISTS. The `compliance-audit` Claude skill (Orcanos QMS repo,
-- ~/.claude/skills/compliance-audit) runs a per-system ISO 27001:2022 Annex A
-- audit and writes its results to a JSON ledger file inside that system's own
-- repo (`Orcanos QMS/compliance/ledger.json`). That's fine for a diffable
-- source of truth, but it means the findings only exist as a file on one
-- machine — nobody can browse them, resolve one, or attach evidence without
-- opening a repo and editing JSON by hand.
--
-- This table is the durable, multi-system home for those findings: one row
-- per Annex A control per audited system (`system_name`), carrying the
-- automated status/evidence from the last skill run PLUS a manual resolution
-- (an operator's answer to "is it documented?", an optional evidence link,
-- who answered, when). The skill's JSON ledger stays the audit trail of *code
-- and infra scans*; this table is where a human closes out the parts a scan
-- can never answer on its own (policy coverage, DPAs, asset inventory, ...).
--
-- MULTI-SYSTEM ON PURPOSE. `system_name` is not a customer account — it is
-- which internal *product* was audited ('orcanos-qms' today; 'account-
-- management' itself, 'traceability-matrix', etc. as the skill is run against
-- them). One control_id (e.g. 'A.5.1') therefore has one row per system, not
-- one row overall — a policy gap in Orcanos QMS says nothing about whether
-- this app has the same gap.
--
-- SEED DATA is the actual 2026-09-15 Orcanos QMS run (93 Annex A controls),
-- carried over from `Orcanos QMS/compliance/ledger.json` so the very first
-- thing this screen shows is real, not empty. `on conflict do nothing` makes
-- re-running this file harmless — it will never overwrite a resolution an
-- operator has already entered.
-- ─────────────────────────────────────────────────────────────────────────

create table if not exists iso27001_controls (
  id                       uuid primary key default gen_random_uuid(),
  system_name              text not null,              -- which internal product was audited, e.g. 'orcanos-qms'
  control_id               text not null,               -- Annex A clause, e.g. 'A.5.1'
  title                    text not null,
  theme                    text not null,               -- Organizational | People | Physical | Technological
  status                   text not null,               -- pass | partial | fail | blocked | not_applicable
  check_ids                jsonb not null default '[]', -- which compliance-audit skill checks produced this status
  evidence                 text,                        -- automated finding text from the last skill run
  last_checked             date,                         -- when the automated scan last touched this control

  -- manual resolution — an operator closing out what a scan alone can't answer
  resolved                 boolean not null default false,
  resolution_answer        text,                        -- e.g. "Yes — see the security policy doc" / "Not yet"
  resolution_evidence_link text,
  resolved_status          text,                        -- the status the operator asserts (pass|partial|fail|not_applicable), independent of the automated `status`
  resolved_by              bigint,                       -- master users.id, no FK (same convention as agent_definitions.created_by)
  resolved_at              timestamptz,

  created_at               timestamptz not null default now(),
  updated_at               timestamptz not null default now()
);

create unique index if not exists idx_iso27001_controls_system_control
  on iso27001_controls(system_name, control_id);

create index if not exists idx_iso27001_controls_system_status
  on iso27001_controls(system_name, status);

comment on table iso27001_controls is
  'ISO/IEC 27001:2022 Annex A control status per internal system, seeded from the '
  'compliance-audit Claude skill''s JSON ledger and resolved here by an operator. '
  'See sql/005_iso27001_controls.sql for the full design note.';

insert into iso27001_controls (system_name, control_id, title, theme, status, check_ids, evidence, last_checked)
values
  ('orcanos-qms', 'A.5.1', 'Policies for information security', 'Organizational', 'partial', '["org.policy_coverage"]'::jsonb, 'org.policy_coverage (partial): A company-wide information security policy exists but does not explicitly name/cover Orcanos QMS as a specific system (user attestation, 2026-09-15).', '2026-09-15'),
  ('orcanos-qms', 'A.5.2', 'Information security roles and responsibilities', 'Organizational', 'pass', '["org.roles_responsibilities"]'::jsonb, 'org.roles_responsibilities (pass): A named owner/responsible person for this system''s security exists (user attestation, 2026-09-15).', '2026-09-15'),
  ('orcanos-qms', 'A.5.3', 'Segregation of duties', 'Organizational', 'partial', '["code.static_authz_review", "org.roles_responsibilities"]'::jsonb, 'code.static_authz_review (partial): Account/tenant scoping enforced by per-endpoint convention (_require_account_member etc.), not a structural guarantee — no DB-level RLS backstop. A new module (fda_510k.py, found during this audit) had an unescaped id-filter IDOR gap; fixed during this audit run. | org.roles_responsibilities (pass): A named owner/responsible person for this system''s security exists (user attestation, 2026-09-15).', '2026-09-15'),
  ('orcanos-qms', 'A.5.4', 'Management responsibilities', 'Organizational', 'partial', '["org.policy_coverage"]'::jsonb, 'org.policy_coverage (partial): A company-wide information security policy exists but does not explicitly name/cover Orcanos QMS as a specific system (user attestation, 2026-09-15).', '2026-09-15'),
  ('orcanos-qms', 'A.5.5', 'Contact with authorities', 'Organizational', 'partial', '["org.incident_response_plan"]'::jsonb, 'org.incident_response_plan (partial): A general incident response plan exists but does not explicitly name Orcanos QMS or its specific escalation path (user attestation, 2026-09-15).', '2026-09-15'),
  ('orcanos-qms', 'A.5.6', 'Contact with special interest groups', 'Organizational', 'partial', '["org.policy_coverage"]'::jsonb, 'org.policy_coverage (partial): A company-wide information security policy exists but does not explicitly name/cover Orcanos QMS as a specific system (user attestation, 2026-09-15).', '2026-09-15'),
  ('orcanos-qms', 'A.5.7', 'Threat intelligence', 'Organizational', 'fail', '["code.dependency_vuln_scan", "org.policy_coverage"]'::jsonb, 'code.dependency_vuln_scan (fail): npm audit found 3 high-severity advisories (ws package, fixes available). Backend requirements.txt has no lockfile and uses floating >= version bounds. | org.policy_coverage (partial): A company-wide information security policy exists but does not explicitly name/cover Orcanos QMS as a specific system (user attestation, 2026-09-15).', '2026-09-15'),
  ('orcanos-qms', 'A.5.8', 'Information security in project management', 'Organizational', 'fail', '["code.secure_sdlc_review"]'::jsonb, 'code.secure_sdlc_review (fail): No CI pipeline runs tests, build, or a security gate (dependency audit/SAST/secret-scan) before deploy. No GitHub Actions found; cloudbuild.yaml deploys with no test step. No branch protection evidence.', '2026-09-15'),
  ('orcanos-qms', 'A.5.9', 'Inventory of information and other associated assets', 'Organizational', 'fail', '["org.asset_inventory"]'::jsonb, 'org.asset_inventory (fail): Orcanos QMS is not yet entered in the org''s asset inventory / Statement of Applicability (user attestation, 2026-09-15).', '2026-09-15'),
  ('orcanos-qms', 'A.5.10', 'Acceptable use of information and other associated assets', 'Organizational', 'partial', '["org.policy_coverage"]'::jsonb, 'org.policy_coverage (partial): A company-wide information security policy exists but does not explicitly name/cover Orcanos QMS as a specific system (user attestation, 2026-09-15).', '2026-09-15'),
  ('orcanos-qms', 'A.5.11', 'Return of assets', 'Organizational', 'pass', '["org.access_review_cadence"]'::jsonb, 'org.access_review_cadence (pass): A periodic (e.g. quarterly) access review is scheduled for this system''s admin/privileged roles (user attestation, 2026-09-15).', '2026-09-15'),
  ('orcanos-qms', 'A.5.12', 'Classification of information', 'Organizational', 'fail', '["org.asset_inventory"]'::jsonb, 'org.asset_inventory (fail): Orcanos QMS is not yet entered in the org''s asset inventory / Statement of Applicability (user attestation, 2026-09-15).', '2026-09-15'),
  ('orcanos-qms', 'A.5.13', 'Labelling of information', 'Organizational', 'fail', '["org.asset_inventory"]'::jsonb, 'org.asset_inventory (fail): Orcanos QMS is not yet entered in the org''s asset inventory / Statement of Applicability (user attestation, 2026-09-15).', '2026-09-15'),
  ('orcanos-qms', 'A.5.14', 'Information transfer', 'Organizational', 'fail', '["code.crypto_review", "supabase.network_restrictions"]'::jsonb, 'supabase.network_restrictions (fail): The production Postgres database''s network restrictions allow 0.0.0.0/0 and ::/0 — no network-layer access control, relying solely on credential secrecy.', '2026-09-15'),
  ('orcanos-qms', 'A.5.15', 'Access control', 'Organizational', 'partial', '["code.static_authz_review", "supabase.rls_policies", "pentest.idor_review"]'::jsonb, 'code.static_authz_review (partial): Account/tenant scoping enforced by per-endpoint convention (_require_account_member etc.), not a structural guarantee — no DB-level RLS backstop. A new module (fda_510k.py, found during this audit) had an unescaped id-filter IDOR gap; fixed during this audit run. | supabase.rls_policies (partial): No table in the project has Row Level Security enabled. All access is correctly centralized through the backend''s service_role key (valid architecture), but the frontend also ships a live anon key for the same project with no RLS as a defense-in-depth backstop. | pentest.idor_review (pass): Previously fixed cross-tenant IDOR issues (C2-C7, H2-H3) verified still intact. A new unescaped-id-filter IDOR/injection gap was found in the (then-new) 510(k) submissions module during this audit and fixed in the same session (backend/fda_510k.py — dossier_id/submission_id now sanitized with urllib.parse.quote before use in PostgREST filter strings).', '2026-09-15'),
  ('orcanos-qms', 'A.5.16', 'Identity management', 'Organizational', 'partial', '["code.authentication_review", "supabase.auth_config"]'::jsonb, 'code.authentication_review (partial): Hardcoded JWT fallback secret (''dev-secret-change-in-prod'') still present in backend/sessions.py (mitigated only by a separate startup validator, not removed at source). No MFA for any role. No rate limiting/lockout on login or password-reset-adjacent endpoints. | supabase.auth_config (partial): Password minimum length is only 6 characters with no complexity rule or HaveIBeenPwned check; MFA (TOTP) is available but not enforced; no session inactivity timeout configured; CAPTCHA disabled on public signup/login.', '2026-09-15'),
  ('orcanos-qms', 'A.5.17', 'Authentication information', 'Organizational', 'partial', '["code.secret_scanning", "supabase.api_key_management"]'::jsonb, 'code.secret_scanning (partial): No live secret currently tracked in git, but a real Orcanos credential exposed historically via .env.test and design/compliance/COMPLIANCE_HANDOFF.md remains in git history and has not been rotated.', '2026-09-15'),
  ('orcanos-qms', 'A.5.18', 'Access rights', 'Organizational', 'partial', '["org.access_review_cadence", "code.static_authz_review"]'::jsonb, 'org.access_review_cadence (pass): A periodic (e.g. quarterly) access review is scheduled for this system''s admin/privileged roles (user attestation, 2026-09-15). | code.static_authz_review (partial): Account/tenant scoping enforced by per-endpoint convention (_require_account_member etc.), not a structural guarantee — no DB-level RLS backstop. A new module (fda_510k.py, found during this audit) had an unescaped id-filter IDOR gap; fixed during this audit run.', '2026-09-15'),
  ('orcanos-qms', 'A.5.19', 'Information security in supplier relationships', 'Organizational', 'partial', '["org.subprocessor_dpa"]'::jsonb, 'org.subprocessor_dpa (partial): Not formally verified. Orcanos (the underlying data platform) holds ISO 27001 certification, which typically includes standard DPA-equivalent terms; Supabase and GCP both offer standard DPAs accepted via their terms of service. No one has explicitly confirmed the signed documents for this system (user attestation, 2026-09-15).', '2026-09-15'),
  ('orcanos-qms', 'A.5.20', 'Addressing information security within supplier agreements', 'Organizational', 'partial', '["org.subprocessor_dpa"]'::jsonb, 'org.subprocessor_dpa (partial): Not formally verified. Orcanos (the underlying data platform) holds ISO 27001 certification, which typically includes standard DPA-equivalent terms; Supabase and GCP both offer standard DPAs accepted via their terms of service. No one has explicitly confirmed the signed documents for this system (user attestation, 2026-09-15).', '2026-09-15'),
  ('orcanos-qms', 'A.5.21', 'Managing information security in the ICT supply chain', 'Organizational', 'fail', '["code.dependency_vuln_scan", "org.subprocessor_dpa"]'::jsonb, 'code.dependency_vuln_scan (fail): npm audit found 3 high-severity advisories (ws package, fixes available). Backend requirements.txt has no lockfile and uses floating >= version bounds. | org.subprocessor_dpa (partial): Not formally verified. Orcanos (the underlying data platform) holds ISO 27001 certification, which typically includes standard DPA-equivalent terms; Supabase and GCP both offer standard DPAs accepted via their terms of service. No one has explicitly confirmed the signed documents for this system (user attestation, 2026-09-15).', '2026-09-15'),
  ('orcanos-qms', 'A.5.22', 'Monitoring, review and change management of supplier services', 'Organizational', 'partial', '["org.subprocessor_dpa"]'::jsonb, 'org.subprocessor_dpa (partial): Not formally verified. Orcanos (the underlying data platform) holds ISO 27001 certification, which typically includes standard DPA-equivalent terms; Supabase and GCP both offer standard DPAs accepted via their terms of service. No one has explicitly confirmed the signed documents for this system (user attestation, 2026-09-15).', '2026-09-15'),
  ('orcanos-qms', 'A.5.23', 'Information security for use of cloud services', 'Organizational', 'fail', '["supabase.network_restrictions", "org.subprocessor_dpa"]'::jsonb, 'supabase.network_restrictions (fail): The production Postgres database''s network restrictions allow 0.0.0.0/0 and ::/0 — no network-layer access control, relying solely on credential secrecy. | org.subprocessor_dpa (partial): Not formally verified. Orcanos (the underlying data platform) holds ISO 27001 certification, which typically includes standard DPA-equivalent terms; Supabase and GCP both offer standard DPAs accepted via their terms of service. No one has explicitly confirmed the signed documents for this system (user attestation, 2026-09-15).', '2026-09-15'),
  ('orcanos-qms', 'A.5.24', 'Information security incident management planning and preparation', 'Organizational', 'partial', '["org.incident_response_plan"]'::jsonb, 'org.incident_response_plan (partial): A general incident response plan exists but does not explicitly name Orcanos QMS or its specific escalation path (user attestation, 2026-09-15).', '2026-09-15'),
  ('orcanos-qms', 'A.5.25', 'Assessment and decision on information security events', 'Organizational', 'partial', '["code.audit_logging_review", "org.incident_response_plan"]'::jsonb, 'code.audit_logging_review (partial): security_audit_log mechanism implemented and wired into login failures and admin actions, but silently no-ops to stdout if migration 009 hasn''t been applied — not confirmed applied to production from code alone. | org.incident_response_plan (partial): A general incident response plan exists but does not explicitly name Orcanos QMS or its specific escalation path (user attestation, 2026-09-15).', '2026-09-15'),
  ('orcanos-qms', 'A.5.26', 'Response to information security incidents', 'Organizational', 'partial', '["org.incident_response_plan"]'::jsonb, 'org.incident_response_plan (partial): A general incident response plan exists but does not explicitly name Orcanos QMS or its specific escalation path (user attestation, 2026-09-15).', '2026-09-15'),
  ('orcanos-qms', 'A.5.27', 'Learning from information security incidents', 'Organizational', 'partial', '["org.incident_response_plan"]'::jsonb, 'org.incident_response_plan (partial): A general incident response plan exists but does not explicitly name Orcanos QMS or its specific escalation path (user attestation, 2026-09-15).', '2026-09-15'),
  ('orcanos-qms', 'A.5.28', 'Collection of evidence', 'Organizational', 'partial', '["code.audit_logging_review"]'::jsonb, 'code.audit_logging_review (partial): security_audit_log mechanism implemented and wired into login failures and admin actions, but silently no-ops to stdout if migration 009 hasn''t been applied — not confirmed applied to production from code alone.', '2026-09-15'),
  ('orcanos-qms', 'A.5.29', 'Information security during disruption', 'Organizational', 'fail', '["org.business_continuity"]'::jsonb, 'org.business_continuity (fail): This system''s backup/DR approach is configured but has not actually been tested with a real restore (user attestation, 2026-09-15).', '2026-09-15'),
  ('orcanos-qms', 'A.5.30', 'ICT readiness for business continuity', 'Organizational', 'fail', '["supabase.backup_pitr", "org.business_continuity"]'::jsonb, 'supabase.backup_pitr (fail): Daily physical backups run reliably (8-day unbroken history), but Point-In-Time Recovery is disabled — recovery is limited to the most recent daily backup boundary (up to ~24h of potential data loss). | org.business_continuity (fail): This system''s backup/DR approach is configured but has not actually been tested with a real restore (user attestation, 2026-09-15).', '2026-09-15'),
  ('orcanos-qms', 'A.5.31', 'Legal, statutory, regulatory and contractual requirements', 'Organizational', 'fail', '["org.legal_regulatory_requirements"]'::jsonb, 'org.legal_regulatory_requirements (fail): Applicable regulatory regimes (this system handles QMS/regulatory data for medical device customers — GDPR/HIPAA-adjacent exposure) have not been identified or mapped to specific controls (user attestation, 2026-09-15).', '2026-09-15'),
  ('orcanos-qms', 'A.5.32', 'Intellectual property rights', 'Organizational', 'fail', '["org.legal_regulatory_requirements"]'::jsonb, 'org.legal_regulatory_requirements (fail): Applicable regulatory regimes (this system handles QMS/regulatory data for medical device customers — GDPR/HIPAA-adjacent exposure) have not been identified or mapped to specific controls (user attestation, 2026-09-15).', '2026-09-15'),
  ('orcanos-qms', 'A.5.33', 'Protection of records', 'Organizational', 'fail', '["code.data_deletion_review", "supabase.backup_pitr"]'::jsonb, 'code.data_deletion_review (fail): delete_user() only removes the master users row — does not cascade to a user''s owned repositories/documents/conversations/usage_logs across accounts, and (unlike delete_account) returns no warning about what isn''t cleaned up. | supabase.backup_pitr (fail): Daily physical backups run reliably (8-day unbroken history), but Point-In-Time Recovery is disabled — recovery is limited to the most recent daily backup boundary (up to ~24h of potential data loss).', '2026-09-15'),
  ('orcanos-qms', 'A.5.34', 'Privacy and protection of PII', 'Organizational', 'fail', '["code.data_masking_review", "code.data_deletion_review", "org.legal_regulatory_requirements"]'::jsonb, 'code.data_masking_review (fail): 19+ call sites in backend/api.py return raw exception text (str(e)) directly in HTTP responses — real information-disclosure gap (tracked internally as L1, still open). | code.data_deletion_review (fail): delete_user() only removes the master users row — does not cascade to a user''s owned repositories/documents/conversations/usage_logs across accounts, and (unlike delete_account) returns no warning about what isn''t cleaned up. | org.legal_regulatory_requirements (fail): Applicable regulatory regimes (this system handles QMS/regulatory data for medical device customers — GDPR/HIPAA-adjacent exposure) have not been identified or mapped to specific controls (user attestation, 2026-09-15).', '2026-09-15'),
  ('orcanos-qms', 'A.5.35', 'Independent review of information security', 'Organizational', 'partial', '["org.policy_coverage"]'::jsonb, 'org.policy_coverage (partial): A company-wide information security policy exists but does not explicitly name/cover Orcanos QMS as a specific system (user attestation, 2026-09-15).', '2026-09-15'),
  ('orcanos-qms', 'A.5.36', 'Compliance with policies, rules and standards for information security', 'Organizational', 'partial', '["org.policy_coverage"]'::jsonb, 'org.policy_coverage (partial): A company-wide information security policy exists but does not explicitly name/cover Orcanos QMS as a specific system (user attestation, 2026-09-15).', '2026-09-15'),
  ('orcanos-qms', 'A.5.37', 'Documented operating procedures', 'Organizational', 'fail', '["code.secure_sdlc_review", "org.policy_coverage"]'::jsonb, 'code.secure_sdlc_review (fail): No CI pipeline runs tests, build, or a security gate (dependency audit/SAST/secret-scan) before deploy. No GitHub Actions found; cloudbuild.yaml deploys with no test step. No branch protection evidence. | org.policy_coverage (partial): A company-wide information security policy exists but does not explicitly name/cover Orcanos QMS as a specific system (user attestation, 2026-09-15).', '2026-09-15'),
  ('orcanos-qms', 'A.6.1', 'Screening', 'People', 'pass', '["org.employee_screening_training"]'::jsonb, 'org.employee_screening_training (pass): Inherited org-wide HR screening/training/NDA program — carried forward unchanged from the 2026-07-29 run.', '2026-09-15'),
  ('orcanos-qms', 'A.6.2', 'Terms and conditions of employment', 'People', 'pass', '["org.employee_screening_training"]'::jsonb, 'org.employee_screening_training (pass): Inherited org-wide HR screening/training/NDA program — carried forward unchanged from the 2026-07-29 run.', '2026-09-15'),
  ('orcanos-qms', 'A.6.3', 'Information security awareness, education and training', 'People', 'pass', '["org.employee_screening_training"]'::jsonb, 'org.employee_screening_training (pass): Inherited org-wide HR screening/training/NDA program — carried forward unchanged from the 2026-07-29 run.', '2026-09-15'),
  ('orcanos-qms', 'A.6.4', 'Disciplinary process', 'People', 'pass', '["org.employee_screening_training"]'::jsonb, 'org.employee_screening_training (pass): Inherited org-wide HR screening/training/NDA program — carried forward unchanged from the 2026-07-29 run.', '2026-09-15'),
  ('orcanos-qms', 'A.6.5', 'Responsibilities after termination or change of employment', 'People', 'pass', '["org.access_review_cadence"]'::jsonb, 'org.access_review_cadence (pass): A periodic (e.g. quarterly) access review is scheduled for this system''s admin/privileged roles (user attestation, 2026-09-15).', '2026-09-15'),
  ('orcanos-qms', 'A.6.6', 'Confidentiality or non-disclosure agreements', 'People', 'pass', '["org.employee_screening_training"]'::jsonb, 'org.employee_screening_training (pass): Inherited org-wide HR screening/training/NDA program — carried forward unchanged from the 2026-07-29 run.', '2026-09-15'),
  ('orcanos-qms', 'A.6.7', 'Remote working', 'People', 'partial', '["org.policy_coverage"]'::jsonb, 'org.policy_coverage (partial): A company-wide information security policy exists but does not explicitly name/cover Orcanos QMS as a specific system (user attestation, 2026-09-15).', '2026-09-15'),
  ('orcanos-qms', 'A.6.8', 'Information security event reporting', 'People', 'partial', '["code.audit_logging_review", "org.incident_response_plan"]'::jsonb, 'code.audit_logging_review (partial): security_audit_log mechanism implemented and wired into login failures and admin actions, but silently no-ops to stdout if migration 009 hasn''t been applied — not confirmed applied to production from code alone. | org.incident_response_plan (partial): A general incident response plan exists but does not explicitly name Orcanos QMS or its specific escalation path (user attestation, 2026-09-15).', '2026-09-15'),
  ('orcanos-qms', 'A.7.1', 'Physical security perimeters', 'Physical', 'pass', '["org.physical_security"]'::jsonb, 'org.physical_security (pass): Orcanos, this system''s hosting/data subprocessor, holds current ISO 27001 certification covering physical security of its data centers (user attestation, 2026-09-15) — satisfies the inherited physical-security controls (A.7.x).', '2026-09-15'),
  ('orcanos-qms', 'A.7.2', 'Physical entry', 'Physical', 'pass', '["org.physical_security"]'::jsonb, 'org.physical_security (pass): Orcanos, this system''s hosting/data subprocessor, holds current ISO 27001 certification covering physical security of its data centers (user attestation, 2026-09-15) — satisfies the inherited physical-security controls (A.7.x).', '2026-09-15'),
  ('orcanos-qms', 'A.7.3', 'Securing offices, rooms and facilities', 'Physical', 'pass', '["org.physical_security"]'::jsonb, 'org.physical_security (pass): Orcanos, this system''s hosting/data subprocessor, holds current ISO 27001 certification covering physical security of its data centers (user attestation, 2026-09-15) — satisfies the inherited physical-security controls (A.7.x).', '2026-09-15'),
  ('orcanos-qms', 'A.7.4', 'Physical security monitoring', 'Physical', 'pass', '["org.physical_security"]'::jsonb, 'org.physical_security (pass): Orcanos, this system''s hosting/data subprocessor, holds current ISO 27001 certification covering physical security of its data centers (user attestation, 2026-09-15) — satisfies the inherited physical-security controls (A.7.x).', '2026-09-15'),
  ('orcanos-qms', 'A.7.5', 'Protecting against physical and environmental threats', 'Physical', 'pass', '["org.physical_security"]'::jsonb, 'org.physical_security (pass): Orcanos, this system''s hosting/data subprocessor, holds current ISO 27001 certification covering physical security of its data centers (user attestation, 2026-09-15) — satisfies the inherited physical-security controls (A.7.x).', '2026-09-15'),
  ('orcanos-qms', 'A.7.6', 'Working in secure areas', 'Physical', 'pass', '["org.physical_security"]'::jsonb, 'org.physical_security (pass): Orcanos, this system''s hosting/data subprocessor, holds current ISO 27001 certification covering physical security of its data centers (user attestation, 2026-09-15) — satisfies the inherited physical-security controls (A.7.x).', '2026-09-15'),
  ('orcanos-qms', 'A.7.7', 'Clear desk and clear screen', 'Physical', 'partial', '["org.policy_coverage"]'::jsonb, 'org.policy_coverage (partial): A company-wide information security policy exists but does not explicitly name/cover Orcanos QMS as a specific system (user attestation, 2026-09-15).', '2026-09-15'),
  ('orcanos-qms', 'A.7.8', 'Equipment siting and protection', 'Physical', 'pass', '["org.physical_security"]'::jsonb, 'org.physical_security (pass): Orcanos, this system''s hosting/data subprocessor, holds current ISO 27001 certification covering physical security of its data centers (user attestation, 2026-09-15) — satisfies the inherited physical-security controls (A.7.x).', '2026-09-15'),
  ('orcanos-qms', 'A.7.9', 'Security of assets off-premises', 'Physical', 'partial', '["org.policy_coverage"]'::jsonb, 'org.policy_coverage (partial): A company-wide information security policy exists but does not explicitly name/cover Orcanos QMS as a specific system (user attestation, 2026-09-15).', '2026-09-15'),
  ('orcanos-qms', 'A.7.10', 'Storage media', 'Physical', 'not_applicable', '[]'::jsonb, 'Not applicable to this system''s architecture.', '2026-09-15'),
  ('orcanos-qms', 'A.7.11', 'Supporting utilities', 'Physical', 'pass', '["org.physical_security"]'::jsonb, 'org.physical_security (pass): Orcanos, this system''s hosting/data subprocessor, holds current ISO 27001 certification covering physical security of its data centers (user attestation, 2026-09-15) — satisfies the inherited physical-security controls (A.7.x).', '2026-09-15'),
  ('orcanos-qms', 'A.7.12', 'Cabling security', 'Physical', 'not_applicable', '[]'::jsonb, 'Not applicable to this system''s architecture.', '2026-09-15'),
  ('orcanos-qms', 'A.7.13', 'Equipment maintenance', 'Physical', 'pass', '["org.physical_security"]'::jsonb, 'org.physical_security (pass): Orcanos, this system''s hosting/data subprocessor, holds current ISO 27001 certification covering physical security of its data centers (user attestation, 2026-09-15) — satisfies the inherited physical-security controls (A.7.x).', '2026-09-15'),
  ('orcanos-qms', 'A.7.14', 'Secure disposal or re-use of equipment', 'Physical', 'pass', '["org.physical_security"]'::jsonb, 'org.physical_security (pass): Orcanos, this system''s hosting/data subprocessor, holds current ISO 27001 certification covering physical security of its data centers (user attestation, 2026-09-15) — satisfies the inherited physical-security controls (A.7.x).', '2026-09-15'),
  ('orcanos-qms', 'A.8.1', 'User endpoint devices', 'Technological', 'partial', '["org.policy_coverage"]'::jsonb, 'org.policy_coverage (partial): A company-wide information security policy exists but does not explicitly name/cover Orcanos QMS as a specific system (user attestation, 2026-09-15).', '2026-09-15'),
  ('orcanos-qms', 'A.8.2', 'Privileged access rights', 'Technological', 'partial', '["supabase.role_privilege_review", "org.access_review_cadence"]'::jsonb, 'supabase.role_privilege_review (partial): No direct Postgres connection available for this audit (Management API token only). Migration SQL shows no custom Postgres roles/grants defined — access control is implemented at the application layer (users.role, is_orcanos_admin), not verified live against pg_roles. | org.access_review_cadence (pass): A periodic (e.g. quarterly) access review is scheduled for this system''s admin/privileged roles (user attestation, 2026-09-15).', '2026-09-15'),
  ('orcanos-qms', 'A.8.3', 'Information access restriction', 'Technological', 'partial', '["code.static_authz_review", "supabase.rls_policies", "pentest.idor_review"]'::jsonb, 'code.static_authz_review (partial): Account/tenant scoping enforced by per-endpoint convention (_require_account_member etc.), not a structural guarantee — no DB-level RLS backstop. A new module (fda_510k.py, found during this audit) had an unescaped id-filter IDOR gap; fixed during this audit run. | supabase.rls_policies (partial): No table in the project has Row Level Security enabled. All access is correctly centralized through the backend''s service_role key (valid architecture), but the frontend also ships a live anon key for the same project with no RLS as a defense-in-depth backstop. | pentest.idor_review (pass): Previously fixed cross-tenant IDOR issues (C2-C7, H2-H3) verified still intact. A new unescaped-id-filter IDOR/injection gap was found in the (then-new) 510(k) submissions module during this audit and fixed in the same session (backend/fda_510k.py — dossier_id/submission_id now sanitized with urllib.parse.quote before use in PostgREST filter strings).', '2026-09-15'),
  ('orcanos-qms', 'A.8.4', 'Access to source code', 'Technological', 'blocked', '["code.source_code_access_review"]'::jsonb, 'code.source_code_access_review (blocked): Requires a review of GitHub org/team membership — not visible from the local checkout.', '2026-09-15'),
  ('orcanos-qms', 'A.8.5', 'Secure authentication', 'Technological', 'fail', '["code.authentication_review", "supabase.auth_config", "pentest.auth_flow_abuse"]'::jsonb, 'code.authentication_review (partial): Hardcoded JWT fallback secret (''dev-secret-change-in-prod'') still present in backend/sessions.py (mitigated only by a separate startup validator, not removed at source). No MFA for any role. No rate limiting/lockout on login or password-reset-adjacent endpoints. | supabase.auth_config (partial): Password minimum length is only 6 characters with no complexity rule or HaveIBeenPwned check; MFA (TOTP) is available but not enforced; no session inactivity timeout configured; CAPTCHA disabled on public signup/login. | pentest.auth_flow_abuse (fail): No rate limiting or lockout after repeated failed login attempts on /auth/local/login or the Orcanos-proxy endpoints (M5, still open). OAuth redirect_uri is not validated server-side against an allowlist (relies solely on the IdP''s own registered-redirect enforcement).', '2026-09-15'),
  ('orcanos-qms', 'A.8.6', 'Capacity management', 'Technological', 'not_applicable', '[]'::jsonb, 'Not applicable to this system''s architecture.', '2026-09-15'),
  ('orcanos-qms', 'A.8.7', 'Protection against malware', 'Technological', 'fail', '["code.dependency_vuln_scan"]'::jsonb, 'code.dependency_vuln_scan (fail): npm audit found 3 high-severity advisories (ws package, fixes available). Backend requirements.txt has no lockfile and uses floating >= version bounds.', '2026-09-15'),
  ('orcanos-qms', 'A.8.8', 'Management of technical vulnerabilities', 'Technological', 'fail', '["code.dependency_vuln_scan"]'::jsonb, 'code.dependency_vuln_scan (fail): npm audit found 3 high-severity advisories (ws package, fixes available). Backend requirements.txt has no lockfile and uses floating >= version bounds.', '2026-09-15'),
  ('orcanos-qms', 'A.8.9', 'Configuration management', 'Technological', 'partial', '["code.change_management_review"]'::jsonb, 'code.change_management_review (partial): A defined Cloud Build pipeline exists (not ad hoc), but it does not enforce tests or a frontend build passing before the Cloud Run deploy step runs.', '2026-09-15'),
  ('orcanos-qms', 'A.8.10', 'Information deletion', 'Technological', 'fail', '["code.data_deletion_review"]'::jsonb, 'code.data_deletion_review (fail): delete_user() only removes the master users row — does not cascade to a user''s owned repositories/documents/conversations/usage_logs across accounts, and (unlike delete_account) returns no warning about what isn''t cleaned up.', '2026-09-15'),
  ('orcanos-qms', 'A.8.11', 'Data masking', 'Technological', 'fail', '["code.data_masking_review"]'::jsonb, 'code.data_masking_review (fail): 19+ call sites in backend/api.py return raw exception text (str(e)) directly in HTTP responses — real information-disclosure gap (tracked internally as L1, still open).', '2026-09-15'),
  ('orcanos-qms', 'A.8.12', 'Data leakage prevention', 'Technological', 'fail', '["code.secret_scanning", "code.data_masking_review"]'::jsonb, 'code.secret_scanning (partial): No live secret currently tracked in git, but a real Orcanos credential exposed historically via .env.test and design/compliance/COMPLIANCE_HANDOFF.md remains in git history and has not been rotated. | code.data_masking_review (fail): 19+ call sites in backend/api.py return raw exception text (str(e)) directly in HTTP responses — real information-disclosure gap (tracked internally as L1, still open).', '2026-09-15'),
  ('orcanos-qms', 'A.8.13', 'Information backup', 'Technological', 'fail', '["supabase.backup_pitr"]'::jsonb, 'supabase.backup_pitr (fail): Daily physical backups run reliably (8-day unbroken history), but Point-In-Time Recovery is disabled — recovery is limited to the most recent daily backup boundary (up to ~24h of potential data loss).', '2026-09-15'),
  ('orcanos-qms', 'A.8.14', 'Redundancy of information processing facilities', 'Technological', 'fail', '["org.business_continuity"]'::jsonb, 'org.business_continuity (fail): This system''s backup/DR approach is configured but has not actually been tested with a real restore (user attestation, 2026-09-15).', '2026-09-15'),
  ('orcanos-qms', 'A.8.15', 'Logging', 'Technological', 'partial', '["code.audit_logging_review", "supabase.audit_logging"]'::jsonb, 'code.audit_logging_review (partial): security_audit_log mechanism implemented and wired into login failures and admin actions, but silently no-ops to stdout if migration 009 hasn''t been applied — not confirmed applied to production from code alone. | supabase.audit_logging (partial): Supabase''s native Postgres/auth audit logging is explicitly disabled on this project (audit_log_disable_postgres=true). The app''s own security_audit_log table exists but no periodic review process or durable off-instance export is confirmed.', '2026-09-15'),
  ('orcanos-qms', 'A.8.16', 'Monitoring activities', 'Technological', 'partial', '["code.audit_logging_review", "supabase.audit_logging"]'::jsonb, 'code.audit_logging_review (partial): security_audit_log mechanism implemented and wired into login failures and admin actions, but silently no-ops to stdout if migration 009 hasn''t been applied — not confirmed applied to production from code alone. | supabase.audit_logging (partial): Supabase''s native Postgres/auth audit logging is explicitly disabled on this project (audit_log_disable_postgres=true). The app''s own security_audit_log table exists but no periodic review process or durable off-instance export is confirmed.', '2026-09-15'),
  ('orcanos-qms', 'A.8.17', 'Clock synchronization', 'Technological', 'not_applicable', '[]'::jsonb, 'Not applicable to this system''s architecture.', '2026-09-15'),
  ('orcanos-qms', 'A.8.18', 'Use of privileged utility programs', 'Technological', 'partial', '["supabase.role_privilege_review"]'::jsonb, 'supabase.role_privilege_review (partial): No direct Postgres connection available for this audit (Management API token only). Migration SQL shows no custom Postgres roles/grants defined — access control is implemented at the application layer (users.role, is_orcanos_admin), not verified live against pg_roles.', '2026-09-15'),
  ('orcanos-qms', 'A.8.19', 'Installation of software on operational systems', 'Technological', 'partial', '["code.change_management_review"]'::jsonb, 'code.change_management_review (partial): A defined Cloud Build pipeline exists (not ad hoc), but it does not enforce tests or a frontend build passing before the Cloud Run deploy step runs.', '2026-09-15'),
  ('orcanos-qms', 'A.8.20', 'Networks security', 'Technological', 'fail', '["pentest.security_headers", "supabase.network_restrictions"]'::jsonb, 'pentest.security_headers (partial): CORS avoids the wildcard-origin + allow_credentials=True combination (credentials hardcoded False), but allow_origins defaults to ''*'' in any deployment where ALLOWED_ORIGINS is unset (M2, tracked as not fully locked down). No CSP or HSTS header is set by the application itself. | supabase.network_restrictions (fail): The production Postgres database''s network restrictions allow 0.0.0.0/0 and ::/0 — no network-layer access control, relying solely on credential secrecy.', '2026-09-15'),
  ('orcanos-qms', 'A.8.21', 'Security of network services', 'Technological', 'not_applicable', '[]'::jsonb, 'Not applicable to this system''s architecture.', '2026-09-15'),
  ('orcanos-qms', 'A.8.22', 'Segregation of networks', 'Technological', 'fail', '["supabase.network_restrictions"]'::jsonb, 'supabase.network_restrictions (fail): The production Postgres database''s network restrictions allow 0.0.0.0/0 and ::/0 — no network-layer access control, relying solely on credential secrecy.', '2026-09-15'),
  ('orcanos-qms', 'A.8.23', 'Web filtering', 'Technological', 'not_applicable', '[]'::jsonb, 'Not applicable to this system''s architecture.', '2026-09-15'),
  ('orcanos-qms', 'A.8.24', 'Use of cryptography', 'Technological', 'pass', '["code.crypto_review", "supabase.api_key_management"]'::jsonb, 'No specific finding recorded.', '2026-09-15'),
  ('orcanos-qms', 'A.8.25', 'Secure development life cycle', 'Technological', 'fail', '["code.secure_sdlc_review"]'::jsonb, 'code.secure_sdlc_review (fail): No CI pipeline runs tests, build, or a security gate (dependency audit/SAST/secret-scan) before deploy. No GitHub Actions found; cloudbuild.yaml deploys with no test step. No branch protection evidence.', '2026-09-15'),
  ('orcanos-qms', 'A.8.26', 'Application security requirements', 'Technological', 'partial', '["pentest.ssrf_review", "pentest.injection_review", "pentest.security_headers", "pentest.input_validation"]'::jsonb, 'pentest.injection_review (pass): Previously fixed injection issues (L3, H1 markdown sanitization, C6 iframe sandboxing) verified still in place. The same-session fix to backend/fda_510k.py (see pentest.idor_review) also closes this module''s PostgREST filter-injection surface. | pentest.security_headers (partial): CORS avoids the wildcard-origin + allow_credentials=True combination (credentials hardcoded False), but allow_origins defaults to ''*'' in any deployment where ALLOWED_ORIGINS is unset (M2, tracked as not fully locked down). No CSP or HSTS header is set by the application itself. | pentest.input_validation (partial): Zip-bomb guard (entry count + total size caps) confirmed intact for zip extraction. General document-upload endpoints have no confirmed server-side max-upload-size or file-type check at the API layer.', '2026-09-15'),
  ('orcanos-qms', 'A.8.27', 'Secure system architecture and engineering principles', 'Technological', 'partial', '["code.static_authz_review", "code.env_separation_review"]'::jsonb, 'code.static_authz_review (partial): Account/tenant scoping enforced by per-endpoint convention (_require_account_member etc.), not a structural guarantee — no DB-level RLS backstop. A new module (fda_510k.py, found during this audit) had an unescaped id-filter IDOR gap; fixed during this audit run. | code.env_separation_review (partial): Dev/test/prod separated by env-file convention, but .env.test previously held a real (not synthetic) Orcanos credential that leaked into git history and has not been rotated.', '2026-09-15'),
  ('orcanos-qms', 'A.8.28', 'Secure coding', 'Technological', 'fail', '["pentest.injection_review", "code.secure_sdlc_review"]'::jsonb, 'pentest.injection_review (pass): Previously fixed injection issues (L3, H1 markdown sanitization, C6 iframe sandboxing) verified still in place. The same-session fix to backend/fda_510k.py (see pentest.idor_review) also closes this module''s PostgREST filter-injection surface. | code.secure_sdlc_review (fail): No CI pipeline runs tests, build, or a security gate (dependency audit/SAST/secret-scan) before deploy. No GitHub Actions found; cloudbuild.yaml deploys with no test step. No branch protection evidence.', '2026-09-15'),
  ('orcanos-qms', 'A.8.29', 'Security testing in development and acceptance', 'Technological', 'fail', '["code.dependency_vuln_scan", "pentest.auth_flow_abuse", "pentest.idor_review", "pentest.ssrf_review", "pentest.injection_review"]'::jsonb, 'code.dependency_vuln_scan (fail): npm audit found 3 high-severity advisories (ws package, fixes available). Backend requirements.txt has no lockfile and uses floating >= version bounds. | pentest.auth_flow_abuse (fail): No rate limiting or lockout after repeated failed login attempts on /auth/local/login or the Orcanos-proxy endpoints (M5, still open). OAuth redirect_uri is not validated server-side against an allowlist (relies solely on the IdP''s own registered-redirect enforcement). | pentest.idor_review (pass): Previously fixed cross-tenant IDOR issues (C2-C7, H2-H3) verified still intact. A new unescaped-id-filter IDOR/injection gap was found in the (then-new) 510(k) submissions module during this audit and fixed in the same session (backend/fda_510k.py — dossier_id/submission_id now sanitized with urllib.parse.quote before use in PostgREST filter strings). | pentest.injection_review (pass): Previously fixed injection issues (L3, H1 markdown sanitization, C6 iframe sandboxing) verified still in place. The same-session fix to backend/fda_510k.py (see pentest.idor_review) also closes this module''s PostgREST filter-injection surface.', '2026-09-15'),
  ('orcanos-qms', 'A.8.30', 'Outsourced development', 'Technological', 'partial', '["org.subprocessor_dpa"]'::jsonb, 'org.subprocessor_dpa (partial): Not formally verified. Orcanos (the underlying data platform) holds ISO 27001 certification, which typically includes standard DPA-equivalent terms; Supabase and GCP both offer standard DPAs accepted via their terms of service. No one has explicitly confirmed the signed documents for this system (user attestation, 2026-09-15).', '2026-09-15'),
  ('orcanos-qms', 'A.8.31', 'Separation of development, test and production environments', 'Technological', 'partial', '["code.env_separation_review"]'::jsonb, 'code.env_separation_review (partial): Dev/test/prod separated by env-file convention, but .env.test previously held a real (not synthetic) Orcanos credential that leaked into git history and has not been rotated.', '2026-09-15'),
  ('orcanos-qms', 'A.8.32', 'Change management', 'Technological', 'partial', '["code.change_management_review"]'::jsonb, 'code.change_management_review (partial): A defined Cloud Build pipeline exists (not ad hoc), but it does not enforce tests or a frontend build passing before the Cloud Run deploy step runs.', '2026-09-15'),
  ('orcanos-qms', 'A.8.33', 'Test information', 'Technological', 'partial', '["code.env_separation_review", "code.secret_scanning"]'::jsonb, 'code.env_separation_review (partial): Dev/test/prod separated by env-file convention, but .env.test previously held a real (not synthetic) Orcanos credential that leaked into git history and has not been rotated. | code.secret_scanning (partial): No live secret currently tracked in git, but a real Orcanos credential exposed historically via .env.test and design/compliance/COMPLIANCE_HANDOFF.md remains in git history and has not been rotated.', '2026-09-15'),
  ('orcanos-qms', 'A.8.34', 'Protection of information systems during audit testing', 'Technological', 'partial', '["org.policy_coverage"]'::jsonb, 'org.policy_coverage (partial): A company-wide information security policy exists but does not explicitly name/cover Orcanos QMS as a specific system (user attestation, 2026-09-15).', '2026-09-15')

on conflict (system_name, control_id) do nothing;
